### ISSUE TITLE
Sequential Layer does not use its name argument

### ISSUE THREAD

**Issue by alaterre** [deepmind/dm-haiku#108]
When running the following code, the final network does not take into account the name provided in the definition of the Sequential layer.

```python
import jax
import jax.numpy as jnp
import haiku as hk

class MLP(hk.Module):
    def __init__(self):
        super(MLP, self).__init__(name="mlp")
        self._network = hk.Sequential(
            layers=[hk.Linear(5), jax.nn.relu, hk.Linear(3), jax.nn.log_softmax],
            name="sequential",
        )

    def __call__(self, x):
        return self._network(x)


if __name__ == "__main__":
    key = jax.random.PRNGKey(42)

    def network_fn(x):
        return MLP()(x)
    net = hk.transform(network_fn)

    dummy = jnp.ones((1, 7))
    params = net.init(key, dummy)
    print(jax.tree_map(lambda x: x.shape, params))
```
Output:
```shell
FlatMapping({
  'mlp/~/linear': FlatMapping({'b': (5,), 'w': (7, 5)}),
  'mlp/~/linear_1': FlatMapping({'b': (3,), 'w': (5, 3)}),
})
```
Whereas I would expect:
```shell
FlatMapping({
  'mlp/sequential/linear': FlatMapping({'b': (5,), 'w': (7, 5)}),
  'mlp/sequential/linear_1': FlatMapping({'b': (3,), 'w': (5, 3)}),
})
```

**Comment by tomhennigan** [comment]
Hi @alaterre , this is actually WAI. Module names are defined when modules are constructed, and are immutable from this point. In this case you construct the Linear layers and pass them into the Sequential.

You can defer construction until call time, but I think (as a user) I might find this a bit of a surprising way to define a network:

```python
def f(x):
  mlp = hk.Sequential([
      lambda x: hk.Linear(300)(x),
      jax.nn.relu,
      lambda x: hk.Linear(100)(x),
      jax.nn.relu,
      lambda x: hk.Linear(10)(x),
  ], name="mlp")
  return mlp(x)

params = f.init(rng, x)
jax.tree_map(jnp.shape, params)
```

```
FlatMapping({
  'mlp/linear': FlatMapping({'b': (300,), 'w': (784, 300)}),
  'mlp/linear_1': FlatMapping({'b': (100,), 'w': (300, 100)}),
  'mlp/linear_2': FlatMapping({'b': (10,), 'w': (100, 10)}),
})
```

I've enumerated a few alternative ways (name scope, deferred construction, no sequential, use the builtin) you could construct an MLP using Sequential and get the desired naming. https://colab.research.google.com/gist/tomhennigan/bbd85e3cb7f3faa64250ffd9ea86ffe7/how-to-to-use-sequential-s-name-for-submodules.ipynb

Hopefully some of the options in there are useful.

**Comment by alaterre** [comment]
@tomhennigan Thx a lot for the clarification! 👍
