### ISSUE TITLE
Specify device for `init` function

### ISSUE THREAD

**Issue by ethanabrooks** [deepmind/dm-haiku#118]
You can tell `jax` to place arrays on a particular device using `jax.device_put` but the `init` function returned from `hk.Transform` appears to perform device placement automatically. Is there a way to specify a device for `init`? If not I am happy to submit a pull request that adds an optional `device` keyword to the `init` function.

**Comment by tomhennigan** [comment]
Hi @ethanabrooks , you can do this by jitting the init function:

```python
f = hk.transform(f)
devices = jax.local_devices()
params = jax.jit(f.init, device=devices[1])(rng, x)
```

Many folks will `pmap` instead of `jit` to replicate their parameters across local devices.
