### ISSUE TITLE
Is there a way to share parameters between methods?

### ISSUE THREAD

**Issue by davisyoshida** [deepmind/dm-haiku#128]
You can write and transform multiple methods on the same module, but it doesn't seem possible to share parameters between them without manually merging the two parameter FlatMappings. It's particularly cumbersome if the shared parameters are used several submodules deep. Is there any more convenient way to accomplish something like this?

**Comment by tomhennigan** [comment]
Hi @davisyoshida , there are two options I'm aware of. Either we have a utility to combine the parameters (`hk.data_structures.merge`) or there is a (somewhat common internally) pattern where you can create "multi transform"  a couple of functions together and give them a shared init.

I've put together an example of both here: https://colab.research.google.com/gist/tomhennigan/cae5ffc066bee24eca56e85d8bf4d351/example-of-transforming-multiple-methods.ipynb

**Comment by davisyoshida** [comment]
@tomhennigan Thanks! The second one seems really useful. Are there edge cases or something which prevent it from being added to Haiku officially?

**Comment by tomhennigan** [comment]
I don't think there are any fundamental blockers to this becoming part of Haiku, I'll follow up with the folks who originally came up with this pattern next week and see if we can upstream their impl (since it has been battle tested by a large number of researchers).

**Comment by ethanluoyc** [comment]
@tomhennigan Looking forward to this being added! I would also love to see some examples of how this is used by researchers at DM. I am recently working on RL using Soft Actor-Critic. Having to perform transforms of multiple methods and sharing parameters between them quicks become unmanageable!

**Comment by altosaar** [comment]
@tomhennigan - thanks so much for going into detail on this! Super helpful.

Given the two options you describe of (1) combining the parameters (`hk.data_structures.merge`) or (2) the 'multi transform' option, I am finding (1) results in more readable and shorter haiku code:

https://github.com/altosaar/variational-autoencoder/blob/master/train_variational_autoencoder_jax.py

I tried the 'multi transform' option, but having a class for VariationalAutoEncoder used more code than applying `hk.transform` separately to the model and variational distributions. The added benefit of keeping it separate is flexibility.

The downside to combining the parameters is a lot of boilerplate:

```
        predicate = lambda module_name, name, value: "model" in module_name
        p_params, q_params = hk.data_structures.partition(predicate, params)
        q_z = variational.apply(q_params, rng_key, x)
        z = q_z.sample(sample_shape=[1], seed=rng_key)
        p_z, p_x_given_z = model.apply(p_params, rng_key, x, z)
```

(This replaces the __call__ method of the multi transform class.)

Are there any ways to avoid such boilerplate while avoiding multi transform functions/classes?

Thanks again! Excited to make more code public using this framework.

**Comment by tomhennigan** [comment]
Hi @altosaar, in your case since you have two separate transforms I would personally avoid `hk.data_structures.{merge,partition}` and just use a tuple instead:

```python
def objective_fn(params: Tuple[hk.Params, hk.Params], ..):
  p_params, q_params = params
  ..

p_params = model.init(..)
q_params = variational.init(..)
params = (p_params, q_params)
objective_fn(params, ..)
```

**Comment by altosaar** [comment]
Awesome thanks so much!! Very much appreciate the tip :)
