### ISSUE TITLE
Haiku allocates memory on GPU despite using CPU jax

### ISSUE THREAD

**Issue by ein-ich** [deepmind/dm-haiku#132]
Hi, I created a new venv and did the following steps:

1. pip install --upgrade pip
2. pip install --upgrade jax jaxlib
3. pip install git+https://github.com/deepmind/dm-haiku
4. pip install -r examples/requirements.txt
5. run python mnist.py in the haiku examples directory

Despite not having installed the GPU version it allocates memory on the GPU (6250MB). I also tested the jax examples, for those it doesn't allocate on the GPU. 
This is a problem when you need to, for example, use both in parallel. Is it supposed to be that way?
![image](https://user-images.githubusercontent.com/25612731/118375658-6274bd00-b5c3-11eb-8511-30c899947a37.png)
![image](https://user-images.githubusercontent.com/25612731/118375691-994ad300-b5c3-11eb-9ef7-1941e4eb405f.png)

**Comment by tomhennigan** [comment]
Hi @ein-ich , I think this is probably TensorFlow not JAX/Haiku allocating on the GPU. I think you should be able to force TF to now see your GPU by adding the following to the start of your program `tf.config.set_visible_devices([], 'gpu')`.

Alternatively you can prevent TF and JAX from seeing your GPU by running with the environment variable `CUDA_VISIBLE_DEVICES` set to the empty string. For example, replace (5) with `CUDA_VISIBLE_DEVICES= python mnist.py`.
