### ISSUE TITLE
Efficient Ways for Saving and Loading weights

### ISSUE THREAD

**Issue by VIGNESHinZONE** [deepmind/dm-haiku#145]
I'm sorry if it's not the right place as I could not find the discussions or forum page.

I was wondering what are some of the most efficient ways to save and load models (also verify it's properly loaded into GPU)?

1, In the docs, its given as [save_the_model using Tensorflow](https://dm-haiku.readthedocs.io/en/latest/notebooks/jax2tf.html?highlight=save#Save-to-disk-as-a-TensorFlow-SavedModel)
2. I also understand that the weights of haiku network are stored in a dictionary, as an example

```
{'linear': {'b': ndarray(..., shape=(300,), dtype=float32),
            'w': ndarray(..., shape=(28, 300), dtype=float32)},
 'linear_1': {'b': ndarray(..., shape=(100,), dtype=float32),
              'w': ndarray(..., shape=(1000, 100), dtype=float32)}}
```

Does haiku have some inbuilt function to save and load models? It becomes crucial in transfer learning tasks.
Thanks in advance,

**Comment by tomhennigan** [comment]
Hi @VIGNESHinZONE , in general we recommend keeping a copy of your Python code which defines your model, and saving weights after training to disk. This provides the most flexibility. You can save weights produced by Haiku using pickle (https://colab.research.google.com/gist/tomhennigan/77a7e4ea04d716e9650bc54acf26f468/saving-and-loading-parameters-using-pickle.ipynb).

The integration with TensorFlow is an example of how to save the implementation of your model (e.g. the operations required to execute your neural network) as a TensorFlow graph, which is a suitable long term serialisation format for ML models. In general the best way to save the implementation of your model is to keep a copy of your Python code. In some situations (e.g. production serving) it is useful to have an intermediate format (like TF graphs) instead.

**Comment by VIGNESHinZONE** [comment]
Thanks for the help :)

**Comment by VIGNESHinZONE** [comment]
Hi @tomhennigan,

I'm in the process of learning Haiku/JAX, and I was running one of the examples MNIST.py given at `/master/examples/mnist.py` on google collab.

https://colab.research.google.com/drive/15JbunNAKhFHZ4Klua-Tx0z84fIzppPpf?usp=sharing

I had tried running the same piece of code on GPU and TPU, here is what I had found

1)  Time taken to execute on GPU -  58 seconds
2)  Time taken to execute on TPU -  246 seconds

I was a bit confused as the speed on TPU was comparable to CPU and wasn't sure if I was doing something wrong. 

Could you please let me know,
Thanks in advance

**Comment by tomhennigan** [comment]
AFAIK Colab runtimes are still using the [legacy TPU stack](https://cloud.google.com/tpu/docs/jax-quickstart-tpu-vm#running_jax_in_a_colab) which has a fairly high overhead per computation or transfer. For a small computation like the MLP in the example these overheads will dominate the execution time of your training loop.

For a smaller example (just with JAX no Haiku) see here: https://colab.research.google.com/gist/tomhennigan/fd878fdd2114df3bbbc01b0a9d77108a/-small-computations-on-cpu-gpu-and-tpu.ipynb

I suspect you'll find that the code would run significantly faster in a [Cloud TPU VM](https://cloud.google.com/blog/products/compute/introducing-cloud-tpu-vms) (which uses the new TPU stack with significantly lower overheads per computation), or you should see more competitive performance from TPU with either the legacy or new stack if you make the network more complex (e.g. ResNet50 or a transformer).

**Comment by VIGNESHinZONE** [comment]
@tomhennigan 
Thanks for a quick response,
I'm fairly new to using TPU for training as I have primarily been a Pytorch user, it was really interesting to learn about TPU. JAX provides features like `pmap` (for parallel GPU's processing and TPU), does Haiku handle them in the background or do we have to correctly add some extra codes to get it working properly.  

https://flax.readthedocs.io/en/latest/howtos/ensembling.html Flax has provided some documentation for it and I was wondering if `haiku` has this additional info.

**Comment by tomhennigan** [comment]
Haiku itself doesn't do anything special to support pmap/vmap. The key idea with Haiku is that once you've `hk.transform`ed your function it is a "pure function" and you can use this directly with `jax.pmap` etc.

For an example of data parallel training with pmap see our resnet/imagenet example https://github.com/deepmind/dm-haiku/blob/master/examples/imagenet/train.py. In there the `train_step` function is parallel mapped across all available GPUs. You might observe that in this code we use Haiku to define a `forward` function with our neural net, and the rest is pure JAX with some other libraries in our ecosystem (e.g. optax for optimization).

As a meta point, its probably worth opening new issues for different questions to help other users who are searching.
