### ISSUE TITLE
Name change or adjustment?

### ISSUE THREAD

**Issue by kallisti5** [deepmind/dm-haiku#2]
Hi!  I'm one of the developers of Haiku and a board member of Haiku, Inc.

We have trademark on the name Haiku around our open-source operating system, as well as a registered logo mark on our Haiku logo.

Haiku has been in development for nearly 20 years now, and usage of the Haiku name for other open source software projects could create confusion.

Please feel free to reach out to Haiku, Inc. if you have any questions.

https://haiku-os.org
https://haiku-inc.org

**Comment by tomhennigan** [comment]
Thank you for the friendly reach-out @kallisti5! The domain and scope of our projects are quite different, and I would not expect users to be confused between Haiku the operating-system and Haiku the python neural network library.

However I'm happy to make some adjustments as suggested to make it clear that these projects are not affiliated and to minimize the potential for any confusion. I propose the following:

1. We will add a note in our read me along the lines of `Disambiguation: If you are looking for Haiku the operating system please see ~link to your project~.`.
2. We will adjust our github project name to dm-haiku (changing the URL), this is inline with the name of the pip package we already use.

Please let me know if this sounds good to you, thanks in advance!

**Comment by kallisti5** [comment]
Good enough! Thanks :-). This originally came up because a few community members pointed it out to the Org.
