### ISSUE TITLE
Running hk.cond with branches using different parameters

### ISSUE THREAD

**Issue by pawelc** [deepmind/dm-haiku#205]
Hi, 

If I have two branches of hk.cond (or hk.switch) using different parameters like in the following code snippet:

```python
import haiku as hk
import jax
import jax.numpy as jnp

def get_a(x):
    a = hk.get_parameter('a',(1,), init=hk.initializers.RandomNormal())
    return a*x

def get_b(x):
    b = hk.get_parameter('b',(1,), init=hk.initializers.RandomNormal())
    return b*x

class MyModel(hk.Module):        
    
    def __call__(self, x):
        return hk.cond(x[0]>0, lambda _: jnp.asarray([1.0]), lambda _: get_b(x), None)        
    
x = jnp.array([2.0])
transform = hk.without_apply_rng(hk.transform(lambda x: MyModel()(x)))
params = transform.init(jax.random.PRNGKey(0), x)
transform.apply(params, x)
```

I get the error:
"true_fun and false_fun output must have same type structure"

Versions: 
* haiku 0.0.5.dev0
* jax 0.2.19

Is such scenario really not supported and what is good practice as workaround ?

**Comment by tomhennigan** [comment]
Hi @pawelc , I think in this case you may need to make use of `hk.running_init` to unconditionally run the branch creating parameters during init and only have the cond during apply. There is a similar example in the docs: https://dm-haiku.readthedocs.io/en/latest/api.html#haiku.running_init

**Comment by pawelc** [comment]
Hi @tamaranorman, thank you. It is working perfectly. Sorry I haven't read all the examples.
