### ISSUE TITLE
Getting rid of states using `hk.without_state()`

### ISSUE THREAD

**Issue by fabiannagel** [deepmind/dm-haiku#267]
I'm using states in my model to capture intermediate activations that I need for testing. For production cases, I don't want to bloat my code with state management.

I expected that `hk.without_state()` was built for this use case. However, the [example](https://dm-haiku.readthedocs.io/en/latest/api.html#without-state) doesn't even use states (?).

I adapted said example to include states:

```
import haiku as hk
import jax
import jax.numpy as jnp

def f(x):
    mod = hk.Linear(10)
    hk.set_state("foo", "bar")
    return mod(x)

rng = jax.random.PRNGKey(42)
x = jnp.zeros([1, 1])

f = hk.without_state(hk.transform_with_state(f))

params = f.init(rng, x)
f.apply(params, rng, x)
```

What I get: `ValueError: If your transformed function uses ``hk.{get,set}_state`` then use ``hk.transform_with_state``.`
I also tried using only `hk.transform(f)` but under the hood that just calls `without_state(transform_with_state(f))` as well.

I'm confused - how do I get rid of states here? This is a hacky way of what I'd like to achieve:

```
f_stateful = hk.transform_with_state(f)
f_stateful = hk.without_apply_rng(f_stateful)

# initialize to obtain an initial state
params, state = f_stateful.init(rng, x)

# wrap initial state & don't return further states
init_stateless = lambda rng, x: f_stateful.init(rng, x)[0]
apply_stateless = lambda params, x: f_stateful.apply(params, state, x)[0]
f = Transformed(init_stateless, apply_stateless)

y = f.apply(params, x)
```

Thanks,
Fabian

**Comment by trevorcai** [comment]
Hey Fabian,
As you've noticed, `without_state` is just syntactic sugar to clean up the method signatures of `hk.transform`-ed functions.

Some options, from least to most hacky:
1. Add a `record_internals` option to your modules, only `hk.{get,set}_state` if that's true.
2. Do your suggestion. Note that XLA prunes unused nodes/constants in a very early compilation pass, so `jax.jit(apply_stateless)` should in theory compile to the same thing as if you avoided state entirely.
3. Option 1, but as a global :^)
4. Monkey-patch `hk.{get,set}_state` to be no-ops.

Trevor
