### ISSUE TITLE
Quick Question about GPU double_buffer for TPU

### ISSUE THREAD

**Issue by evanatyourservice** [deepmind/dm-haiku#284]
https://github.com/deepmind/dm-haiku/blob/main/examples/imagenet/dataset.py#L163

Should I use double buffering for TPU as well? Is TPU allocation similar to GPU described in the function's docstring, where the allocation is held over batch to batch?

**Comment by tomhennigan** [comment]
Double buffering is not needed for TPU.

FYI the resnet example is well optimised for TPU, you should find that it achieves good performance if you use a ["new" Cloud TPU VM](https://cloud.google.com/blog/products/compute/introducing-cloud-tpu-vms) which runs directly on the TPU host machine. This is documented in the [Cloud TPU VM JAX quickstart](https://cloud.google.com/tpu/docs/jax-quickstart-tpu-vm) guide.

**Comment by evanatyourservice** [comment]
Thank you so much!
