### ISSUE TITLE
Hi. Is there an example that I can deploy it on ONNX for Javascript or C#?

### ISSUE THREAD

**Issue by JonathanSum** [deepmind/dm-haiku#285]
Sorry for this super noob question to professional people in Deep Mind.
Hi. I did a couple of Pytorch projects before and I was able to deploy them in Javascript with ONNX. 
Thus, how about dm-haiku? Is there a way to deploy it in a language that is other than Python? I hope the model can be used in C# or Javascript. Moreover, I heard some people saying we can convert jax to tf or keras to deploy it to javascript. If so, can we do it on dm-haiku?

One more question, another option of deploying it is only running the CPU-only version of it for trained model on other languages, such as in Javascript in web assembly. For that, I need to know what I need to install and their size(because it will require the user to download it and I see the web assembly version of the javascript version of numpy and sklearn)
Thank you if you can answer it.🤣😂

**Comment by tomhennigan** [comment]
Hi @JonathanSum, Haiku relies on JAX providing support for staging out (e.g. turning a Haiku program into a TensorFlow graph) and/or compilation to executable code (e.g. via the XLA compiler).

Haiku itself doesn't have any specific code to support deployment, but there are a few options in JAX that you can use.

I suspect the simplest route for what you want to do would be to convert from JAX->TF and then from TF->ONNX. Then you would be able to use the tools you are familiar with from PyTorch for deployment to Javascript.

I've put together an example here: https://colab.research.google.com/gist/tomhennigan/5e3d316ec6ebd81500a660155770e34a/example-of-jax-haiku-onnx.ipynb

If you need more support I think it would be best to open a question on the JAX repository about how to run JAX code in the browser. If you find a way to do so generally for JAX, then deploying a JAX program using Haiku should "just work".

**Comment by JonathanSum** [comment]
Thank you. I will close this issue in 2 days if there are no one wants to reply here.
I hope I can use your example on Unity for building a 3d model.
