### ISSUE TITLE
Pytorch hooks equivalent

### ISSUE THREAD

**Issue by joaogui1** [deepmind/dm-haiku#289]
Is there an equivalent to [Pytorch Hooks](https://pytorch.org/docs/stable/notes/modules.html#module-hooks) in Haiku (or JAX itself)?

**Comment by tomhennigan** [comment]
Haiku has three "forward hook" style APIs:

  - [`hk.custom_getter`](https://dm-haiku.readthedocs.io/en/latest/api.html?highlight=intercept_methods#custom-getter) allows you to intercept calls to `get_parameter` or `get_state`, getters are run after initial values are created (e.g. after the init function).
  - [`hk.custom_creator`](https://dm-haiku.readthedocs.io/en/latest/api.html?highlight=intercept_methods#custom-creator) allows you to intercept the creation of parameters or state (e.g. before the init function is called). These only run when parameters are created (e.g. as part of your `init` function).
  - [`hk.intercept_methods`](https://dm-haiku.readthedocs.io/en/latest/api.html?highlight=intercept_methods#haiku.intercept_methods) allows you to intercept module method calls (e.g. `__call__`) and change arguments or return values.

We've used these APIs to implement features such as support for [mixed precision training](https://github.com/deepmind/dm-haiku/blob/main/haiku/_src/mixed_precision.py) and a lot of people use `custom_getter` to add `lax.stop_gradient` calls.

**Comment by joaogui1** [comment]
Thank you very much!
