### ISSUE TITLE
version 0.0.6 update broke google-colab today

### ISSUE THREAD

**Issue by sokrypton** [deepmind/dm-haiku#313]
I'm getting this error:
AttributeError: module 'jaxlib.xla_extension' has no attribute 'PmapFunction'

**Comment by tomhennigan** [comment]
Thanks for the report, the version of JAX in Colab is quite old (5 releases behind!). I'll chat with the Colab+JAX teams to see if we can get it updated.

For now you will need to manually upgrade the version of JAX that is installed in your Colab. Here is an example: https://colab.research.google.com/gist/tomhennigan/d3114f83c64a6a79374589a96cf2eb5a/upgrade-jax-in-colab.ipynb . The important part is:

    !pip install --upgrade pip
    !pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html

**Comment by tomhennigan** [comment]
The JAX version in Colab is now 0.3.4 which should be sufficient for the latest Haiku :).
