### ISSUE TITLE
suggestion: remove if-statements from dropout layer

### ISSUE THREAD

**Issue by sokrypton** [deepmind/dm-haiku#319]
Due to the rate check, it's not possible to modify the rate parameter dynamically without recompiling the entire graph. 
https://github.com/deepmind/dm-haiku/blob/main/haiku/_src/basic.py#L316
 ```python
 if rate < 0 or rate >= 1:
    raise ValueError("rate must be in [0, 1).")

  if rate == 0.0:
    return x
```

**Comment by LenaMartens** [comment]
great idea, thanks for the suggestion!
