### ISSUE TITLE
ValueError: `hk.running_init` must be used as part of an `hk.transform`

### ISSUE THREAD

**Issue by dorost1234** [deepmind/dm-haiku#321]
Hi
I am running this example from Haiku tutorial: https://dm-haiku.readthedocs.io/en/latest/api.html
```
import haiku as hk
import jax
import jax.numpy as jnp
import numpy as np

def g(x):
  return hk.Linear(1)(x)
g = hk.transform(g)
print(g)
init_rng = hk.next_rng_key() if hk.running_init() else None
x = jnp.ones([1, 1])
params = hk.lift(g.init, name='f_lift')(init_rng, x)
print(params)
out = g.apply(params, None, x)
```
getting this error:
```
    init_rng = hk.next_rng_key() if hk.running_init() else None
  File "/users/dara/libs/anaconda3/envs/haiku/lib/python3.8/site-packages/haiku/_src/transform.py", line 467, in running_init
    base.assert_context("running_init")
  File "/users/dara/libs/anaconda3/envs/haiku/lib/python3.8/site-packages/haiku/_src/base.py", line 281, in assert_context
    raise ValueError(
ValueError: `hk.running_init` must be used as part of an `hk.transform`
```

could you have a look please? thanks

**Comment by tomhennigan** [comment]
Hi @dorost1234 , I think the docs you are following are from an advanced feature called `hk.lift` which you should not typically need when starting out with Haiku.

I would suggest following this tutorial instead: https://dm-haiku.readthedocs.io/en/latest/notebooks/basics.html

You may also find out MNIST example useful: https://github.com/deepmind/dm-haiku/blob/main/examples/mnist.py
