### ISSUE TITLE
AttributeError: partially initialized module 'jax' has no attribute '_src' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by Waterkin** [deepmind/dm-haiku#385]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/41324537/166085370-b9a1f1b4-2fa2-4494-a4ec-e75b4c6cc05f.png">

<img width="579" alt="image" src="https://user-images.githubusercontent.com/41324537/166085387-d7802ac6-d32f-4666-83db-a8aae8c6ef4f.png">

<img width="839" alt="image" src="https://user-images.githubusercontent.com/41324537/166085389-06871300-ae87-490c-9b74-497a792e70c2.png">

Not knowing what's wrong. Thanks for answering!~

**Comment by tomhennigan** [comment]
Hi @Waterkin, I'm not sure what's up here but I suspect you can fix this by updating JAX to the latest version. You can find instructions to do so here: https://github.com/google/jax#installation

**Comment by Waterkin** [comment]
> Hi @Waterkin, I'm not sure what's up here but I suspect you can fix this by updating JAX to the latest version. You can find instructions to do so here: https://github.com/google/jax#installation

Thanks for your reply, Tom~

**Comment by furysnack** [comment]
> > Hi @Waterkin, I'm not sure what's up here but I suspect you can fix this by updating JAX to the latest version. You can find instructions to do so here: https://github.com/google/jax#installation
> 
> Thanks for your reply, Tom~

Did you solve this problem？
