### ISSUE TITLE
jax2tf example crashes 

### ISSUE THREAD

**Issue by djbyrne** [deepmind/dm-haiku#389]
Hi,

I was trying to get the jax2tf notebook working https://github.com/deepmind/dm-haiku/blob/main/docs/notebooks/jax2tf.ipynb
but it crashes when calculating the gradients with the following error.

```
SystemError                               Traceback (most recent call last)
[<ipython-input-19-8bf9ef037a2a>](https://localhost:8080/#) in <module>()
     19 
     20 for step, (images, labels) in enumerate(ds_train.take(6001)):
---> 21   loss = train_step(images, labels)
     22   if step % 1000 == 0:
     23     print(f"Step {step}: {loss.numpy()}")

1 frames
[<ipython-input-19-8bf9ef037a2a>](https://localhost:8080/#) in train_step(images, labels)
     14     loss += 1e-4 * sum(map(tf.nn.l2_loss, params))
     15 
---> 16   grads = tape.gradient(loss, params)
     17   opt.apply(grads, params)
     18   return loss

SystemError: <built-in function len> returned a result with an error set
```

Any ideas what might be causing it?

**Comment by tomhennigan** [comment]
Thanks for the report, this looks like a bug in jax2tf or TensorFlow. I've created a reproducer without Haiku and submitted a bug to the JAX team, let's track it there: google/jax#10586.

**Comment by tomhennigan** [comment]
Thanks for highlighting, this will be fixed in the next release of JAX (needs google/jax@eb2dbaa23051fd5f52097362f4e5e569b2d6dd1e) and Haiku (needs 89be8fa4a678e59a0178b5d5234b72d2e986f3a5).
