### ISSUE TITLE
Is there any code examples about how to use attention in Haiku?

### ISSUE THREAD

**Issue by Waterkin** [deepmind/dm-haiku#392]
Hello, 
I am trying to add an attention layer to LSTM, but not find any examples about using Haiku.MultiHeadAttention.
Is there any code examples about how to use Attention Layer in Haiku?

**Comment by tomhennigan** [comment]
Our transformer example includes a [subclass of MHA](https://github.com/deepmind/dm-haiku/blob/main/examples/transformer/model.py#L25) and you can see [it being used here](https://github.com/deepmind/dm-haiku/blob/main/examples/transformer/model.py#L104-L109).
