### ISSUE TITLE
FutureWarning: jax.tree_util.tree_multimap() is deprecated

### ISSUE THREAD

**Issue by sokrypton** [deepmind/dm-haiku#406]
Looks like dm-haiku is still using tree_multimap() which is now deprecated (resulting in annoying "future warning" messages with the latest jax) 

```
/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py:189: FutureWarning: jax.tree_util.tree_multimap() is deprecated. Please use jax.tree_util.tree_map() instead as a drop-in replacement.
  'instead as a drop-in replacement.', FutureWarning)
```

**Comment by njwfish** [comment]
Just curious when there will be a release that includes this fix?

**Comment by sokrypton** [comment]
the `jax.tree_map` was already fixed in the latest dm-haiku, but now there are a bunch of other functions that are being deprecated (aka moved from `jax.tree_???` to `jax.tree_util.tree_???`)

**Comment by njwfish** [comment]
Ah I see, hopefully those will be fixed soon. The warnings are quite annoying haha

**Comment by sokrypton** [comment]
Looks like I don't have the power to reopen the issue. @tomhennigan ?

**Comment by sokrypton** [comment]
In the meantime, you can add this at the top of your code to hide all the warnings: 😄 
```python
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
```
