### ISSUE TITLE
'Config' object has no attribute 'jax_experimental_name_stack'

### ISSUE THREAD

**Issue by Honza9723** [deepmind/dm-haiku#448]
Dear All,

today, my JAX & Haiku code that I was using for quite a long time suddenly stopped working. Simple parameter initialization for a vanilla feed-forward network (which previously worked without any problems) throws an error.

`θ_p_krs = policy_krs.init(init_key,representative_input_krs)`

Returns following error message

`AttributeError                            Traceback (most recent call last)
[<ipython-input-18-dc1b73614781>](https://localhost:8080/#) in <module>()
      1 '''(13.2) Initialize network parameters '''
      2 '''(13.2.1) Krusell-Smith policies '''
----> 3 θ_p_krs = policy_krs.init(init_key,representative_input_krs)
      4 θ_μ_krs = multip_krs.init(init_key,representative_input_krs)
      5 '''(13.2.2) Distribution-based policies '''

4 frames
[/usr/local/lib/python3.7/dist-packages/haiku/_src/module.py](https://localhost:8080/#) in wrapped(self, *args, **kwargs)
    406       f = functools.partial(unbound_method, self)
    407       f = functools.partial(run_interceptors, f, method_name, self)
--> 408       if jax.config.jax_experimental_name_stack and module_name:
    409         local_module_name = module_name.split("/")[-1]
    410         f = jax.named_call(f, name=local_module_name)

AttributeError: 'Config' object has no attribute 'jax_experimental_name_stack'`

Could somebody suggest to me, how to fix this issue? Again, I used this code for more than a month, and today, it suddenly stopped working, I guess it is due to some dependency change in core JAX.

Best,
Honza

**Comment by tomhennigan** [comment]
It sounds like you are either using a newer version of Haiku or an older version of JAX than you were previously when the code was working.

We are running unit tests against JAX `0.3.5`, I would suggest making sure your version of JAX is at least as new as that.

We should also work correctly with newer versions of JAX (internally we test Haiku at HEAD against JAX at HEAD.

**Comment by Honza9723** [comment]
Thank you!
