### ISSUE TITLE
Middle Layer Output

### ISSUE THREAD

**Issue by rusuanjun007** [deepmind/dm-haiku#451]
Hi, Is it possible to get the middle layer outputs from a model? For example, If I use 

model  = haiku.nets.ResNet18(num_classes=1000)

Is there a way that can I get the output before the last classification layer or any middle CONV layer output?

**Comment by IanQS** [comment]
At least for the model you've mentioned I don't think that you can without going in and making changes to the source files.

In general you can either: use multi-transform to output a tuple of `(final-layer, desired-output)` or I think you can use a module called Oryx from TF probability

**Comment by rusuanjun007** [comment]
@IanQS 
Hi IanQS, Thanks for your answer. I'll try to modify the source files of haiku.nets.ResNet18.
