### ISSUE TITLE
`hk.vmap` raises error despite `split_rng=hk.running_init()`

### ISSUE THREAD

**Issue by smonsays** [deepmind/dm-haiku#498]
When using `hk.vmap` to map over a leading axis while sharing parameters, I get an error when trying to set `split_rng=True` or `split_rng=hk.running_init()`. Here is a small example:
```python
import haiku as hk
import jax


class BatchedModule(hk.Module):
    def __init__(self, output_dim):
        super().__init__()
        # self.module = hk.Linear(output_dim)
        self.module = hk.nets.MLP([10] + [output_dim])

    def __call__(self, input_batch):
        # The following line raises the error
        return hk.vmap(self.module, split_rng=hk.running_init())(input_batch)


inputs = jax.random.normal(rng := jax.random.PRNGKey(0), (128, 13))
batched_linear = hk.transform_with_state(lambda x: BatchedModule(output_dim=11)(x))
params, state = batched_linear.init(rng, inputs)
out = batched_linear.apply(params, state, rng, inputs)
```
which raises
```
ValueError: hk.vmap does not support setting split_rng to True during initialization because it assumes parameters are always shared along the mapped dimension. Consider switching the value of `split_rng` to False during initialization through `hk.running_init()`.
```
I am not sure if I am doing something wrong, but at least the error message is misleading since `hk.running_init()` is already set here.

**Comment by LenaMartens** [comment]
Sorry, my bad for the confusing error message: you should set `split_rng` to `False` during initialization, meaning `split_rng=(not hk.running_init())`. 

I'll send a change updating the error message, let me know if the above works!

**Comment by smonsays** [comment]
Oh of course, that makes sense and works. Thank you!
