### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by cgarciae** [deepmind/dm-haiku#51]
I've noticed `_src` has become quite large. I think eventually splitting it up into folders makes more sense. We could have:

- `nn`
- `initializers`
- `regularizers`
- `losses`
- `metrics`

**Comment by tomhennigan** [comment]
Thanks for the suggestion! The folder structure here matches Sonnet (2) and our experience with managing a flat structure there has been that it works quite well for navigating code and has not been a maintenance burden.

Additionally we don't expect the root of `_src` to grow much over the next year or two, we may add more `nets` and `examples` (which are already in subdirs) but the core set of features and modules has grown extremely slowly compared to other libraries, so I don't think we need to do this pre-emptively.

Haiku (and Sonnet) both strongly encourage development to occur outside the core library (e.g. DeepMind recently released ACME which includes [Haiku implementations of a number of common RL agents/networks](https://github.com/deepmind/acme/tree/5b577f1f7d007316d82411f77abc491be8c4585f/acme/jax)) and new modules are added to the core library very rarely (as you can see from #46 we are quite conservative 😄 ). 

So I think for now we should maintain the structure as is.
