### ISSUE TITLE
Batch Norm causing int 32 error in gradient function

### ISSUE THREAD

**Issue by dcaustin33** [deepmind/dm-haiku#513]
Hi when I use a batch norm layer I get the error TypeError: grad requires real- or complex-valued inputs (input dtype that is a sub-dtype of np.inexact), but got int32. If you want to use Boolean- or integer-valued inputs, use vjp or set allow_int to True. Code below - I believe it traces back to the "counter" within the exponential moving average. 

```
class MLP(hk.Module):
  """One hidden layer perceptron, with normalization."""

  def __init__(
      self,
  ):
    super().__init__()
    self._hidden_size = 10
    self._output_size = 1
    bn_config = dict()
    bn_config.setdefault("create_scale", True)
    bn_config.setdefault("create_offset", True)
    bn_config.setdefault("decay_rate", 0.999)
    self._bn_config = bn_config

  def __call__(self, inputs: jnp.ndarray, is_training: bool) -> jnp.ndarray:
    out = hk.Linear(output_size=self._hidden_size, with_bias=True)(inputs)
    out = hk.BatchNorm(**self._bn_config)(out, is_training=is_training)
    out = jax.nn.relu(out)
    out = hk.Linear(output_size=self._output_size, with_bias=False)(out)
    return out    

def forward(x):
  module = MLP()
  return module(x, True)

rng = jax.random.PRNGKey(0)
rng, init_rng = jax.random.split(rng)
forward = hk.transform_with_state(forward)
params, state = forward.init(init_rng, jnp.ones((4, 3)))

x = jax.random.normal(init_rng, (4, 3))
y = jnp.array([1.0, 2.1, 1.4, 1.2])
def loss_fn(state, params, x, y):
    logits = forward.apply(params, state, None, x)
    print(logits)
    return ((logits - y)**2).mean()
grad_fn = jax.grad(loss_fn)(state, params, x, y)
```

Error message:
TypeError                                 Traceback (most recent call last)
/home/ec2-user/cifar/cifar-code/Untitled.ipynb Cell 5 in <cell line: 7>()
      [5](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a224177735f6563325f736d616c6c227d/home/ec2-user/cifar/cifar-code/Untitled.ipynb#W4sdnNjb2RlLXJlbW90ZQ%3D%3D?line=4)     print(logits)
      [6](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a224177735f6563325f736d616c6c227d/home/ec2-user/cifar/cifar-code/Untitled.ipynb#W4sdnNjb2RlLXJlbW90ZQ%3D%3D?line=5)     return ((logits - y)**2).mean()
----> [7](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a224177735f6563325f736d616c6c227d/home/ec2-user/cifar/cifar-code/Untitled.ipynb#W4sdnNjb2RlLXJlbW90ZQ%3D%3D?line=6) grad_fn = jax.grad(loss_fn)(state, params, x, y)

    [... skipping hidden 4 frame]

File ~/.local/lib/python3.9/site-packages/jax/_src/api.py:1109, in _check_input_dtype_revderiv(name, holomorphic, allow_int, x)
   1106 if (dtypes.issubdtype(aval.dtype, np.integer) or
   1107     dtypes.issubdtype(aval.dtype, np.bool_)):
   1108   if not allow_int:
-> 1109     raise TypeError(f"{name} requires real- or complex-valued inputs (input dtype "
   1110                     f"that is a sub-dtype of np.inexact), but got {aval.dtype.name}. "
   1111                     "If you want to use Boolean- or integer-valued inputs, use vjp "
   1112                     "or set allow_int to True.")
   1113 elif not dtypes.issubdtype(aval.dtype, np.inexact):
   1114   raise TypeError(f"{name} requires numerical-valued inputs (input dtype that is a "
   1115                   f"sub-dtype of np.bool_ or np.number), but got {aval.dtype.name}.")

TypeError: grad requires real- or complex-valued inputs (input dtype that is a sub-dtype of np.inexact), but got int32. If you want to use Boolean- or integer-valued inputs, use vjp or set allow_int to True.

**Comment by nlsfnr** [comment]
Although this answer probably comes too late, I hope that it might still help others with a similar issue.

`jax.grad` differentiates the given function with respect to its first argument (assuming that `argnums=0`, which is the default).

To fix your issue, either set `argnums=1` or swap the order of the arguments `state` and `params` to you loss function.
