### ISSUE TITLE
Modules not setting individually when setting them with list comprehension 

### ISSUE THREAD

**Issue by renecotyfanboy** [deepmind/dm-haiku#514]
Hello everyone, 

I encountered a strange behaviour when trying to set several modules with different attributes using pythonic features. I reproduced a minimal example here : 

```
import jax.numpy as jnp
import haiku as hk

class TestModule(hk.Module):

    def __init__(self, to_add):
        super(TestModule, self).__init__()
        self.to_add = to_add

    def __call__(self, x):

        return x + self.to_add

to_add_list = [1*jnp.ones((1,)), 2*jnp.ones((1,)), 3*jnp.ones((1,))]

func_list = [hk.without_apply_rng(hk.transform(lambda x: TestModule(to_add)(x))) for to_add in to_add_list]

for func in func_list:

    print(func.apply(None, jnp.ones((1,))))
```

This outputs [4.], [4.], [4.], instead of the desired [2.], [3.], [4.]

In this snippet, we would like to set 3 modules which add 1, 2 and 3 to the input, and when using them, all the three modules are set to add 3 (only the last one should do this). 

I got this issue with haiku 0.0.6 and 0.07 and upgrading jax/jaxlib did not change anything. I have almost no idea about why it behaves this way, and defining the functions under jax.jit or pmap do not fix either.

**Comment by nlsfnr** [comment]
Haiku modules should be seen purely as functions. They do not save any data, including e.g. `to_add`.

Since `self.to_add` is not a trainable parameter, the only way to access it inside `TestModule.__call__` is by using state. See the [official documentation](https://dm-haiku.readthedocs.io/en/latest/api.html#haiku.transform_with_state) for `haiku.transform_with_state`.

**Comment by renecotyfanboy** [comment]
Rethinking of this for unknown reason : the issue may originate from the use of lambda function to define this list of modules.

```
import jax.numpy as jnp
import haiku as hk

class TestModule(hk.Module):

    def __init__(self, to_add):
        super(TestModule, self).__init__()
        self.to_add = to_add

    def __call__(self, x):

        return x + self.to_add

to_add_list = [1*jnp.ones((1,)), 2*jnp.ones((1,)), 3*jnp.ones((1,))]

def build_module(to_add):

    def f(x):
        return TestModule(to_add)(x)

    return f

func_list = [hk.without_apply_rng(hk.transform(build_module(to_add))) for to_add in to_add_list]

for func in func_list:

    print(func.apply(None, jnp.ones((1,))))
```

This snippet works as intended!

> Haiku modules should be seen purely as functions. They do not save any data, including e.g. to_add.

I can't imagine NN-layers working without saving any metadata such as the entry/output size or number of features etc. Maybe your comment was more about keeping mutable arguments in module properties, however JAX array are immutable.
