### ISSUE TITLE
FutureWarning: jax.tree_* is deprecated

### ISSUE THREAD

**Issue by njwfish** [deepmind/dm-haiku#529]
Following #406 many jax.tree operations have been deprecated and moved to `jax.tree_* -> jax.tree_util.tree_*`. in the latest release resulting in many future warnings.

It would be nice to get a hk spot release that fixes these warnings.

**Comment by tomhennigan** [comment]
Hi @njwfish , I'll cut a release next week to address this. Thanks for the heads up.

**Comment by tomhennigan** [comment]
I just published https://github.com/deepmind/dm-haiku/releases/tag/v0.0.8 which should get rid of the deprecation warnings 😄
