### ISSUE TITLE
hk.ResetCore Requires A Batch Dimension in Inputs

### ISSUE THREAD

**Issue by Hwhitetooth** [deepmind/dm-haiku#53]
Hi Haiku team,

Thanks for opensourcing such a great library!

It looks like hk.ResetCore requires the leading dimension of the inputs to be the batch dimension: https://github.com/deepmind/dm-haiku/blob/master/haiku/_src/recurrent.py#L638. However, other RNN cores, like LSTM (https://github.com/deepmind/dm-haiku/blob/master/haiku/_src/recurrent.py#L264), do not have such a requirement. In fact, I found this mismatch when I was using an RNN without a batch dimension in the inputs.

Could you perhaps change hk.ResetCore so that it also works with inputs without a batch dimension?

Thanks!
Zeyu

**Comment by trevorcai** [comment]
This should now work!

**Comment by Hwhitetooth** [comment]
Thanks, @trevorcai !
