### ISSUE TITLE
Haiku equivalent to Keras `Lambda`

### ISSUE THREAD

**Issue by alembcke** [deepmind/dm-haiku#562]
Is there a Haiku equivalent to the below Keras implementation?

```py
Xmax = MaxPooling2D(pool_size=(1,10))(X)
Xmax = Lambda(lambda x1 : x1*0.3)(Xmax)

Xavg = AvgPool2D(pool_size=(1,10))(X)
Xavg = Lambda(lambda x1 : x1*0.7)(Xavg)

X = Add()([Xmax, Xavg])
X = Lambda(lambda y : K.squeeze(y,2))(X)
```

I can't seem to find anything that does the equivalent of the `Lambda` layer in the above.  I would preferably want to do this within `hk.Sequential`.

**Comment by alembcke** [comment]
Nevermind, it looks as though `hk.BatchApply` is what I was looking for.

**Comment by trevorcai** [comment]
n.b. you don't need to wrap everything in a haiku module if there's no state. hk.sequential just accepts a sequence of callables, so something like:
`hk.Sequential([lambda t: t + 1, jax.nn.relu, hk.Linear(4)])` works as well
