### ISSUE TITLE
Announcing Elegy!

### ISSUE THREAD

**Issue by cgarciae** [deepmind/dm-haiku#62]
Hey, I created this framework called Elegy with a couple of friends, its Keras-like framework based on Haiku. The experience of creating a higher-level API for training using Haiku has been interesting, we've had to wrap some of Haiku's modules and functions to enable additional features but the overall experience has been very positive! It would be great if some of these features eventually went back to Haiku in the future if you are interested.

https://poets-ai.github.io/elegy/

Feel free to close the issue.

**Comment by tomhennigan** [comment]
Congratulations on the launch! In general our philosophy with Haiku is to keep the library fairly minimal and focussed just on providing NN modules (with an API that is [quite familiar to Sonnet users](https://github.com/deepmind/sonnet)) and making it really easy for you to build your own modules.

I think it's really great that frameworks like Elegy can make use of Haiku and provide additional functionality that many users want (e.g. losses, training loops, evaluation etc).
