### ISSUE TITLE
MyModule.__init__ runs every time 'apply' is called

### ISSUE THREAD

**Issue by bionicles** [deepmind/dm-haiku#63]
```
import haiku as hk


class MyModule(hk.Module):
    def __init__(self):
        super().__init__(name="MyModule")
        print("MyModule.__init__ ran")

    def __call__(self, x):
        print("MyModule.__call__ ran")
        return x + 1


def forward(x):
    return MyModule()(x)


rng = hk.PRNGSequence(420)
fwd = hk.transform(forward)
params = fwd.init(next(rng), 1)
x = 0
for _ in range(10):
    x = fwd.apply(params, x)
```

```
MyModule.__init__ ran
MyModule.__call__ ran
MyModule.__init__ ran
MyModule.__call__ ran
MyModule.__init__ ran
MyModule.__call__ ran
MyModule.__init__ ran
MyModule.__call__ ran
MyModule.__init__ ran
MyModule.__call__ ran
MyModule.__init__ ran
MyModule.__call__ ran
MyModule.__init__ ran
MyModule.__call__ ran
MyModule.__init__ ran
MyModule.__call__ ran
MyModule.__init__ ran
MyModule.__call__ ran
MyModule.__init__ ran
MyModule.__call__ ran
MyModule.__init__ ran
MyModule.__call__ ran
```

is this intended? It caused my module to break eventually because it pulled different hyperparameters at different invocations

**Comment by cgarciae** [comment]
Hey @bionicles, this is expected unless you use `jit` somewhere.

**Comment by bionicles** [comment]
yikes

**Comment by tomhennigan** [comment]
As @cgarciae says this is WAI.

The two functions you get back from `hk.transform` are pure functions (the module instances inside these functions are temporary and don't live beyond your call to init or apply) and you can use `jit` (or `pmap`) to make them run fast. In your example you should change the loop to:

```
apply_jit = jax.jit(fwd.apply)
for _ in range(10):
  x = apply_jit(params, x)
```

In general JAX programs rely heavily on JIT compilation with XLA to get good performance so I would suggest in general trying to structure your program like this (a tight loop calling a compiled function.
