### ISSUE TITLE
Dealing with conditionally constant state

### ISSUE THREAD

**Issue by joaogui1** [deepmind/dm-haiku#67]
How could I add a constant state to my haiku module?
Specifically I would want something like this:
```python
class MyModule(hk.Module):
  def __init__(output_size, const, name):
    if const = True:
      self.b = hk.conts(jnp.ones(output_size)) //won't be updated when adding gradient
    else:
      self.b = jnp.zeros(output_size) //will get updated when adding gradient
```

**Comment by cgarciae** [comment]
@joaogui1 Short answer:
* `hk.get_pameters` for trainable parameters
* `hk.get_state` for non trainable (but updatable state)
* For true constant stuff just use a constant jax array.

Long Answers: You need to understand a bit how hooks work. In most hook systems you have use hooks **unconditionally**, this doesn't mean you can use branching, its that you have to declare the hook outside of the conditional parts of the code. For a discussion on this check out this section on Elegy's documentation: [Module Hooks: Functional Style](http://127.0.0.1:8000/guides/module-system/#module-hooks-functional-style). 

**Note:** Elegy's hook system is not the same as Haiku's, but most of the basic rules apply.

**Comment by joaogui1** [comment]
Thanks for the answer @cgarciae! 
The thing is that I wanted to deal with the conditional part only on `__init__`, and use the same `__call__` method irrespective of the variable being trainable or not, is that impossible?

**Comment by cgarciae** [comment]
@joaogui1 Ahh, thats easy then! For some reason I thought this was during `__call__`. Just do something like this:

```python
class MyModule(hk.Module):
  def __init__(output_size, const, name):
    if const = True:
      self.b = jnp.ones(output_size) //won't be updated when adding gradient
    else:
      self.b = hk.get_parameter("b", [output_size], init=jnp.zeros) //will get updated when adding gradient
```

**Comment by cgarciae** [comment]
@joaogui1 I do worry you will try to this module inside the `__call__` method of another module because things might break.

**Comment by cgarciae** [comment]
The safest solution, as suggested in the document I sent you, is to do something like this:

```python
class MyModule(hk.Module):
  def __init__(output_size, const, name):
    b = hk.get_parameter("b", [output_size], init=jnp.zeros) //will get updated when adding gradient
    if const = True:
      self.b = jnp.ones([output_size]) //won't be updated when adding gradient
    else:
      self.b = b
```

This way `hk.get_parameter("b", ...)`get called no matter what.

**Comment by joaogui1** [comment]
Thank you very much!
