### ISSUE TITLE
Changing input batch size causes `UnexpectedTracerError`

### ISSUE THREAD

**Issue by ujjwalnur** [deepmind/dm-haiku#671]
Given a basic `VGG_D` model, the following happens 
```

import jax
import haiku as hk
from timeit import timeit
import time


keys_seq = hk.PRNGSequence(0)
@jax.jit
def _forward_fn(x):
   # This model is already defined and has a correct format.
    model = vgg.VGG_D(num_classes=1000)
    return model(x)


def test():
    for i in range(1000):
       # The following fails due to batch size being 2
       # inp_x = jax.random.normal(key=rng_key, shape=(2, 3, 224, 224))
       # The following line works
        inp_x = jax.random.normal(key=rng_key, shape=(1, 3, 224, 224))
        out = model.apply(params, x=inp_x)
    return None

model = hk.without_apply_rng(hk.transform(_forward_fn))

dummy_x = jax.random.normal(key=next(keys_seq), shape=(1, 3, 224, 224))

params = model.init(rng=next(keys_seq), x=dummy_x)

seconds = timeit("test()", globals=globals(), number=10)
ms_per_pass = (seconds / (1e4)) * 1000
print(ms_per_pass)
```

The error is broadly the following :  

```
jax.errors.UnexpectedTracerError: Encountered an unexpected tracer. A function transformed by JAX had a side effect, allowing for a reference to an intermediate value with type float32[3,3,3,64] wrapped in a DynamicJaxprTracer to escape the scope of the transformation.
JAX transformations require that functions explicitly return their outputs, and disallow saving intermediate values to global state.

```

I understand that this might be due to the requirement that `jax.jit()` expects all array shapes to be statically known. Then what is the correct and recommended way to deal with variable batch sizes ?

I found a discussion [here](https://stackoverflow.com/questions/66711706/jax-jit-and-dynamic-shapes-a-regression-from-tensorflow) and according to it, it seems that I must also have access to the actual number of samples in a batch. So, if I do `model.init()` with a dummy input with `batch size` of `512` and have an input data with a total of `511` batches, then I should do `zero_padding` to have a `batch_size` of `512` and mask, the last dimension to do all calculations.

Is this is the recommended way ?

**Comment by tomhennigan** [comment]
Hi @ujjwalnur, the issue here is probably that you have applied `jax.jit` to your function before passing it to Haiku:

```python
@jax.jit
def _forward_fn(x):
  ..
```

I think in newer version of Haiku (or at least [at head](https://github.com/deepmind/dm-haiku/blob/4b0401225221c2fba092903edfab15fc6e102642/haiku/_src/transform.py#L349)) we have a runtime warning which should fire for this case.

To fix, apply jit **after** `hk.transform`:

```python
# no jit here
def _forward_fn(x):
  ..

model = hk.without_apply_rng(hk.transform(_forward_fn))

init_model = jax.jit(model.init)
apply_model = jax.jit(model.apply)
```

> I understand that this might be due to the requirement that jax.jit() expects all array shapes to be statically known. Then what is the correct and recommended way to deal with variable batch sizes ?

`jax.jit` will recompile for each different batch size you pass in.

**Comment by ujjwalnur** [comment]
@tomhennigan Thanks for this. This definitely helps. Surprisingly, if the behavior differed in previous versions, it is not well documented. I will check again.
