### ISSUE TITLE
Is there a way to load parameters from Flax model?

### ISSUE THREAD

**Issue by llCurious** [deepmind/dm-haiku#687]
I wonder if there is a recommended approach to load parameters from Flax model. Specifically, the flax model is from Huggingface, in the format of msgpack. For a same model architecture like Bert, i want to load the parameters to Haiku-implemented Bert.

**Comment by llCurious** [comment]
BTW, an alternative approach is directly loading from Pytorch model, I wonder in this case is there a recommended practice. Thx in advance.

**Comment by tomhennigan** [comment]
Hi @llCurious , there isn't a recommended way of doing this and people often write one off scripts to migrate checkpoints from one framework to another (e.g. load using original script, change checkpoint format and write back to disk).

Often there is a small amount of manual work required (e.g. changing parameter names, tree structures etc) which is non trivial to automate.
