### ISSUE TITLE
Support model examples

### ISSUE THREAD

**Issue by llCurious** [deepmind/dm-haiku#688]
Hi, I wonder does Haiku plans to support more diverse models like Bert, LLAMA, etc. It would be awesom to have these examples provided.

**Comment by davisyoshida** [comment]
@llCurious I have a haiku port of LLaMA if you want to use it: https://github.com/davisyoshida/llama-haiku

**Comment by llCurious** [comment]
That's awesom. Thank you for providing the implementation example.

**Comment by tomhennigan** [comment]
Hi @llCurious, so far we've kept the examples in Haiku itself fairly sparse and the community have provided a number of different implementations of popular papers outside of the core Haiku repo.

**Comment by llCurious** [comment]
Yep, make sense. I wonder whether you know the community provides example for Bert model?

**Comment by davisyoshida** [comment]
@llCurious There are Flax implementations of BERT etc if you need to experiment with them.

**Comment by llCurious** [comment]
Yep, this would be of great help to me. Thx a lot @davisyoshida

**Comment by davisyoshida** [comment]
[Here's](https://github.com/huggingface/transformers/tree/main/src/transformers/models) the directory with the code for all the HuggingFace models. For example you can look at `bert/modeling_flax_bert.py` for BERT.
