### ISSUE TITLE
Dot

### ISSUE THREAD

**Issue by joaogui1** [deepmind/dm-haiku#79]
So, why does dot.py exist and why is it not public? ( FWIW I'm in favor of keeping it alive and making it public)

**Comment by tomhennigan** [comment]
It is public, just in experimental: https://dm-haiku.readthedocs.io/en/latest/api.html#to-dot

**Comment by joaogui1** [comment]
Silly me, I searched dot, to_graph, render and pretty much every other piece of code haha. Thanks!

**Comment by tomhennigan** [comment]
No worries! It is intentionally not very well advertised.. Right now there are quite a few sharp edges so this is certainly an experimental feature. For example the following fails because we do not correctly implement call primitives:

```python
import haiku as hk
import jax
import jax.numpy as jnp

def f(x):
  assert x.shape == (), x.shape  # AssertionError: (2,)

x = jnp.ones([2])
hk.experimental.to_dot(jax.pmap(f))(x)
```

If you remove the assert you can still visualize the result, but you should be aware that the leading dimension is retained when you visualize the mapped computation (which it should not be).

We have some thoughts about simplifying the impl (e.g. relying on `named_call` to add the clusters) which I believe will help us soften these sharp edges, but its not top of the list at the moment.

**Comment by asmith26** [comment]
Hi there, I've been trying to plot the model on the [first page of the doc](https://dm-haiku.readthedocs.io/en/latest/index.html#haiku-documentation), but I can't seem to get it to work:

```python
import haiku as hk
import jax
import jax.numpy as jnp

def forward(x):
    mlp = hk.nets.MLP([300, 100, 10])
    return mlp(x)

forward = hk.transform(forward)

rng = jax.random.PRNGKey(42)
x = jnp.ones([8, 28 * 28])
params = forward.init(rng, x)
logits = forward.apply(params, rng, x)

print(hk.experimental.to_dot(forward.apply)(params, rng, x))
```

In a Jupyter notebook all I'm getting out is:
<details>
<summary>Haiku output:</summary>
```python
digraph G {
rankdir = TD;
compound = true;
label = <<b>apply_fn</b>>;
fontsize=38;
labelloc = t;
stylesheet = <
  data:text/css,
  @import url(https://fonts.googleapis.com/css?family=Roboto:400,700);
  svg text {
    font-family: 'Roboto';
  }
  .node text {
    font-size: 12px;
  }
>
subgraph cluster_140542404109392 {
  style="rounded,filled";
  fillcolor="#F0F5F5";
  color="#14234B;";
  pad=0.1;
  fontsize=27;
  label = <<b>mlp (__init__)</b>>;
  labelloc = t;
subgraph cluster_140542404108592 {
  style="rounded,filled";
  fillcolor="#F0F5F5";
  color="#14234B;";
  pad=0.1;
  fontsize=19;
  label = <<b>mlp/~/linear_0 (__init__)</b>>;
  labelloc = t;
}  // subgraph cluster_140542404108592
subgraph cluster_140542404109152 {
  style="rounded,filled";
  fillcolor="#F0F5F5";
  color="#14234B;";
  pad=0.1;
  fontsize=19;
  label = <<b>mlp/~/linear_1 (__init__)</b>>;
  labelloc = t;
}  // subgraph cluster_140542404109152
subgraph cluster_140542404110272 {
  style="rounded,filled";
  fillcolor="#F0F5F5";
  color="#14234B;";
  pad=0.1;
  fontsize=19;
  label = <<b>mlp/~/linear_2 (__init__)</b>>;
  labelloc = t;
}  // subgraph cluster_140542404110272
}  // subgraph cluster_140542404109392
subgraph cluster_140542404110352 {
  style="rounded,filled";
  fillcolor="#F0F5F5";
  color="#14234B;";
  pad=0.1;
  fontsize=27;
  label = <<b>mlp</b>>;
  labelloc = t;
140542403646176 [label=<<b>max</b><br/>f32[8,300]>,  id="node140542403646176", shape=rect, style="filled", tooltip=" ", fontcolor="black", color="#FFDB13", fillcolor="#FFF26E"];
140542403646288 [label=<<b>max</b><br/>f32[8,100]>,  id="node140542403646288", shape=rect, style="filled", tooltip=" ", fontcolor="black", color="#FFDB13", fillcolor="#FFF26E"];
subgraph cluster_140542404111072 {
  style="rounded,filled";
  fillcolor="#F0F5F5";
  color="#14234B;";
  pad=0.1;
  fontsize=19;
  label = <<b>mlp/~/linear_0</b>>;
  labelloc = t;
140542403646736 [label=<<b>dot_general</b><br/>f32[8,300]>,  id="node140542403646736", shape=rect, style="filled", tooltip=" ", fontcolor="black", color="#FFDB13", fillcolor="#FFF26E"];
140542403646848 [label=<<b>broadcast_in_dim</b><br/>f32[8,300]>,  id="node140542403646848", shape=rect, style="filled", tooltip=" ", fontcolor="black", color="#FFDB13", fillcolor="#FFF26E"];
140542403646960 [label=<<b>add</b><br/>f32[8,300]>,  id="node140542403646960", shape=rect, style="filled", tooltip=" ", fontcolor="black", color="#FFDB13", fillcolor="#FFF26E"];
}  // subgraph cluster_140542404111072
1405424037790400 -> 140542403646736;
1405424037802720 -> 140542403646736;
1405424037803840 -> 140542403646848;
140542403646736 -> 140542403646960;
140542403646848 -> 140542403646960;
subgraph cluster_140542404111632 {
  style="rounded,filled";
  fillcolor="#F0F5F5";
  color="#14234B;";
  pad=0.1;
  fontsize=19;
  label = <<b>mlp/~/linear_1</b>>;
  labelloc = t;
140542403647184 [label=<<b>dot_general</b><br/>f32[8,100]>,  id="node140542403647184", shape=rect, style="filled", tooltip=" ", fontcolor="black", color="#FFDB13", fillcolor="#FFF26E"];
140542403647296 [label=<<b>broadcast_in_dim</b><br/>f32[8,100]>,  id="node140542403647296", shape=rect, style="filled", tooltip=" ", fontcolor="black", color="#FFDB13", fillcolor="#FFF26E"];
140542403647408 [label=<<b>add</b><br/>f32[8,100]>,  id="node140542403647408", shape=rect, style="filled", tooltip=" ", fontcolor="black", color="#FFDB13", fillcolor="#FFF26E"];
}  // subgraph cluster_140542404111632
140542403646176 -> 140542403647184;
1405424036455040 -> 140542403647184;
1405424036456160 -> 140542403647296;
140542403647184 -> 140542403647408;
140542403647296 -> 140542403647408;
subgraph cluster_140542404112192 {
  style="rounded,filled";
  fillcolor="#F0F5F5";
  color="#14234B;";
  pad=0.1;
  fontsize=19;
  label = <<b>mlp/~/linear_2</b>>;
  labelloc = t;
140542403647632 [label=<<b>dot_general</b><br/>f32[8,10]>,  id="node140542403647632", shape=rect, style="filled", tooltip=" ", fontcolor="black", color="#FFDB13", fillcolor="#FFF26E"];
140542403647744 [label=<<b>broadcast_in_dim</b><br/>f32[8,10]>,  id="node140542403647744", shape=rect, style="filled", tooltip=" ", fontcolor="black", color="#FFDB13", fillcolor="#FFF26E"];
140542403647856 [label=<<b>output</b><br/><b>add</b><br/>f32[8,10]>,  id="node140542403647856", shape=rect, style="filled,bold", tooltip=" ", fontcolor="black", color="#0053D6", fillcolor="#AABFFF"];
}  // subgraph cluster_140542404112192
140542403646288 -> 140542403647632;
1405424036457280 -> 140542403647632;
1405424036458400 -> 140542403647744;
140542403647632 -> 140542403647856;
140542403647744 -> 140542403647856;
}  // subgraph cluster_140542404110352
140542403646960 -> 140542403646176;
140542404108656 -> 140542403646176;
140542403647408 -> 140542403646288;
140542404110496 -> 140542403646288;
1405424037803840 [label=<<b>args[0]: mlp/~/linear_0/b</b><br/>f32[300]> id="node1405424037803840", shape=rect, style="filled", fontcolor="black", color="#FF8A4F", fillcolor="#FFDEAF"];
1405424037802720 [label=<<b>args[0]: mlp/~/linear_0/w</b><br/>f32[784,300]> id="node1405424037802720", shape=rect, style="filled", fontcolor="black", color="#FF8A4F", fillcolor="#FFDEAF"];
1405424036456160 [label=<<b>args[0]: mlp/~/linear_1/b</b><br/>f32[100]> id="node1405424036456160", shape=rect, style="filled", fontcolor="black", color="#FF8A4F", fillcolor="#FFDEAF"];
1405424036455040 [label=<<b>args[0]: mlp/~/linear_1/w</b><br/>f32[300,100]> id="node1405424036455040", shape=rect, style="filled", fontcolor="black", color="#FF8A4F", fillcolor="#FFDEAF"];
1405424036458400 [label=<<b>args[0]: mlp/~/linear_2/b</b><br/>f32[10]> id="node1405424036458400", shape=rect, style="filled", fontcolor="black", color="#FF8A4F", fillcolor="#FFDEAF"];
1405424036457280 [label=<<b>args[0]: mlp/~/linear_2/w</b><br/>f32[100,10]> id="node1405424036457280", shape=rect, style="filled", fontcolor="black", color="#FF8A4F", fillcolor="#FFDEAF"];
1405424037790400 [label=<<b>args[2]</b><br/>f32[8,784]> id="node1405424037790400", shape=rect, style="filled", fontcolor="black", color="#FF8A4F", fillcolor="#FFDEAF"];
140542404108656 [label=<<b>0.0</b>> shape=rect, style="filled", fontcolor="black", color="#A261FF", fillcolor="#E6D6FF"];
140542404110496 [label=<<b>0.0</b>> shape=rect, style="filled", fontcolor="black", color="#A261FF", fillcolor="#E6D6FF"];
} // digraph G
```
</details>

I was hoping to obtain an output something like (created with [Keras](https://keras.io/api/utils/model_plotting_utils/)):

![image](https://user-images.githubusercontent.com/6988036/102701248-ea40e000-424c-11eb-94b7-cdbdb736b934.png)


**Am I using this correctly/expecting the correct sort of output?**

Many thanks for any help, and for this fantastic lib!

**Comment by tomhennigan** [comment]
Hi @asmith26, we return the graphviz dot as a string, to render this you can use the `graphviz` Python library (or I think there are other options).

```python
dot = hk.experimental.to_dot(forward.apply)(params, rng, x)

import graphviz
graphviz.Source(dot)
```

Here is a complete example in colab: https://colab.research.google.com/gist/tomhennigan/800b302df11f41b377522a4ef8b10ff9/example-of-plotting-graphviz-in-colab.ipynb

FYI unlike Keras we are actually visualising the JAX computations per layer (e.g. Linear is `dot + (broadcast+add)`) so the graph is a bit more complicated than your example. I have separately been working on a utility to show a tabular summary of module method calls which may be closer to what you want (it shows input/output shape, module name and config etc).

Tabulate should be submitted this week and will be in the next Haiku release.

**Comment by asmith26** [comment]
Thanks so much for your help and detailed information & colab @tomhennigan , just what I needed - looking forward to trying out Tabulate too :)

**Comment by tomhennigan** [comment]
With @LenaMartens help I have added a notebook showing the new summarisation feature as well as how to visualise with `graphviz.Source` in Colab. https://dm-haiku.readthedocs.io/en/latest/notebooks/visualization.html

**Comment by asmith26** [comment]
This is really useful, many thanks @tomhennigan !

**Comment by asmith26** [comment]
Question: shouldn't dropout be showing up in this example?

```python
import graphviz
import haiku as hk
import jax
import jax.numpy as jnp

@hk.transform
def forward(x):
    x = hk.Linear(10)(x)
    x = hk.dropout(jax.random.PRNGKey(42), 0.1, x)
    return x

rng = jax.random.PRNGKey(42)
x = jnp.ones([8, 28 * 28])
params = forward.init(rng, x)

dot = hk.experimental.to_dot(forward.apply)(params, rng, x)
graphviz.Source(dot)
```

![image](https://user-images.githubusercontent.com/6988036/104067572-4a4af680-51fb-11eb-8bf1-0e3cd131a432.png)

and: `print(hk.experimental.tabulate(forward)(x))`

![image](https://user-images.githubusercontent.com/6988036/104067585-51720480-51fb-11eb-95e2-03bf84db41e2.png)

(Possibly the purple is dropout in the dot diagram, although it does not appear to be within Tabulate.)

**Comment by tomhennigan** [comment]
The purple items in the vis are constants. Because you have "closed over" the random key for dropout your mask is a constant value and JAX is just baking this in to the program. A reasonable fix here would be to use `hk.next_rng_key()` for your dropout RNG key rather than `jax.random.PRNGKey(42)`.

Wrt tabulate, we've implemented dropout as a function rather than a Module (since it has no parameters this seemed to make sense) and tabulate only shows Module method calls. You can convert any function to a module class using `hk.to_module`. There is another issue you will run into, which is that tabulate filters to "interesting" method calls, those are defined as methods returning something (e.g. we filter `__init__`) and modules which have parameters. I think the latter is perhaps a confusing default that should be removed.

Here is a tweaked version of your code with Dropout as a module and using an RNG key split from the one you pass to `f.apply`:

https://colab.research.google.com/gist/tomhennigan/ea75bb90b186becf42ac6a7f8fba1cc1/visualising-dropout.ipynb

**Comment by asmith26** [comment]
Very helpful, many thanks @tomhennigan (also I didn't know about the `rng = hk.next_rng_key()` functionality, so thanks!)
