### ISSUE TITLE
Escaped tracers only in initialization

### ISSUE THREAD

**Issue by mattwescott** [deepmind/dm-haiku#84]
My `f.apply` works but `f.init` has escaped tracers. For a reproduction, see `Issues` in [this notebook](https://github.com/mattwescott/probability/blob/d2f97d70efc4b36d41cf08848d8ad7f8e881cd5a/discussion/examples/autoregressive_flow_on_jax.ipynb)

Does this combination of working apply and failing init point to an issue with Haiku? The motivating tfp issue is [here](https://github.com/tensorflow/probability/issues/1169)

**Comment by tomhennigan** [comment]
Hi @mattwescott, it looks like inside TFP they are doing a JAX transform (e.g. jit/pmap or similar) and the module you pass in is getting called inside this inner transformation (that is where the tracers are coming from).

Haiku (and other OO JAX libraries) need you to use [wrapped versions of JAX transforms](https://dm-haiku.readthedocs.io/en/latest/api.html#jax-transforms) if you are using JAX transforms that close over the usage of Modules without explicitly passing state. In Haiku this means inside your `hk.transform`ed function you need to use `hk.jit` etc if you are wrapping code that makes use of a module.

For modules that only make use of parameters/rng in Haiku (e.g. if you are using `hk.transform` and not `hk.transform_with_state`) there is a "trick" you can use to handle these inner JAX transforms, which is making use of the `jax.core.eval_context()` context manager inside your modules). This will cause values to not be eagerly "staged out" to the inner transform (unless they have been explicitly passed in to it) and will stop parameters becoming (deeper) tracers.

Here is an updated copy of your notebook with the trick applied: https://colab.research.google.com/gist/tomhennigan/94ce417598baeb0b8db703981ea83992/autoregressive_flow_on_jax-ipynb-txt.ipynb. I've wrapped this up as a decorator (`run_in_eval_context`) to make the delta from your original code small (defining and using the decorator is the only meaningful difference).

The other approach (as you highlighted in the TFP issue) is to transform each Haiku module into a pure function and thread the state yourself.

I hope that's useful for you! We've recently been developing some "guides" for Haiku (e.g. [using Haiku with jax2tf](https://dm-haiku.readthedocs.io/en/latest/notebooks/jax2tf.html)) and perhaps we should do the same with TFP to document this.

**Comment by mattwescott** [comment]
Thanks @tomhennigan, this was helpful.

In this example, the `unroll_loop` option on `MaskedAutoregressiveFlow` is enough to avoid inner transforms in sampling. Your version probably works with more bijector types. Really none of these options is satisfying, maybe I'm missing something. For now will move this over to tensorflow/probability#1176
