### ISSUE TITLE
ResNet: downsample happening in the wrong convolution?

### ISSUE THREAD

**Issue by mil-ad** [deepmind/dm-haiku#85]
https://github.com/deepmind/dm-haiku/blob/fd5e52ac4b9a6a9cb79d639c3b845f6a9014ad03/haiku/_src/nets/resnet.py#L82

I may be remembering this wrong but shouldn't the downsample in the BasicBlock happen in the first convolution (`conv_0`) instead of `conv_1`?

Update: I just compared this with Torch's implementation and they do something similar for bottleneck layers, but not the basic layers.

**Comment by tomhennigan** [comment]
Thank you for the report @mil-ad, for bottleneck blocks we are intentionally following the ResNet v1.5 definition ([as torchvision](https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py#L86-L91) and others do) and placing the stride on the second conv.

For the basic blocks it looks like we are not striding correctly (strides should be applied on the first but not second conv).

Before submitting a fix I am going to run some sweeps to see if this has a significant impact on our resnet/imagenet benchmark (and maybe some others) such that we can better inform users when we release a new version of the library.

**Comment by tamaranorman** [comment]
One thing to note is that this model was originally based on the algorithm used here https://github.com/tensorflow/tpu/blob/master/models/official/resnet/resnet_model.py#L524. It may be worth also flagging the result with them or seeing if they have a reason for this slight change in architecture.

**Comment by tomhennigan** [comment]
Sorry for the delay in patching this (non work related things have been somewhat distracting..).

I swept with/without the change for ResNet 18 and 34 using our "standard" imagenet/resnet training script (essentially the same as the imagenet example we ship with Haiku). I also swept `resnet_v2` and a few seeds per combination.

This bug caused the smaller ResNets to perform better than they should, ResNet18 has a ~1% regression in top-1 after 90 epochs and ResNet34 regresses by ~0.5%. Larger ResNets (50 et al) are not affected.

![tensorboard](https://user-images.githubusercontent.com/28017/102883943-b3371e00-4448-11eb-9ee5-93e5e9b47225.png)

Thank you very much for reporting this!
