### ISSUE TITLE
Extra arguments for Sequential

### ISSUE THREAD

**Issue by mil-ad** [deepmind/dm-haiku#87]
[The documentation](https://dm-haiku.readthedocs.io/en/latest/api.html#haiku.Sequential) for `Sequential` suggests using a custom module when extra arguments are needed:

```
  Another restriction is that it is not possible to have extra arguments in the
  :meth:`__call__` method that are passed to the constituents of the module -
  for example, if there is a :class:`BatchNorm` module in :class:`Sequential`
  and the user wishes to switch the ``is_training`` flag. If this is the desired
  use case, the recommended solution is to subclass :class:`Module` and
  implement ``__call__``:

      >>> class CustomModule(hk.Module):
      ...   def __call__(self, x, is_training):
      ...     x = hk.Conv2D(32, 4, 2)(x)
      ...     x = hk.BatchNorm(True, True, 0.9)(x, is_training)
      ...     x = jax.nn.relu(x)
      ...     return x
  ```

How does this custom module exactly help with the problem outlined above? It's not like it can be placed inside a `Sequential` can it? Is this meant to replace `Sequential`? I think the documentation here could be slightly improved to remove confusion. 

One useful use case of Sequntial is dynamically adding layers in a loop. Is the recommended Haiku way to handle that is using `is_instance()` inside my `__call__` to provide `is_training` when necessary?

**Comment by mil-ad** [comment]
Unrelated: is it ok to instantiate stateful Haiku modules inside `__call__` like snippet above? I'm assuming `transform` magic takes care of that and we don't get a new module in every call to `__call__`?

**Comment by tomhennigan** [comment]
The example in the docs is intended to replace the sequential, perhaps we should call it `MyCustomSequential` or something like that?

I think our main point is that for `Sequential` making the calling convention "do the right thing" (e.g. thread `is_training` or other kwargs) would make the module quite complex and could potentially be brittle. Our experience from Sonnet 1 and 2 is that it is often more readable to subclass and pass is_training to submodules as needed.

You could implement something on top of Haiku if you prefer to have a more feature rich sequential:

```python
import inspect

import jax
import jax.numpy as jnp
import haiku as hk

class FancySequential(hk.Module):
  def __init__(self, layers, name=None):
    super().__init__(name=name)
    self.layers = tuple(layers)

  def __call__(self, x, is_training):
    for layer in self.layers:
      try:
        x = layer(x, is_training=is_training)
      except TypeError:
        x = layer(x)
    return x

def f(x):
  layers = []
  for _ in range(3):
    layers.append(hk.Conv2D(32, 4, 2))
    layers.append(hk.BatchNorm(True, True, 0.9))
    layers.append(jax.nn.relu)

  x = FancySequential(layers)(x, True)
  return x.sum()

x = jnp.ones([1, 224, 224, 3])
f = hk.transform_with_state(f)
params, state = f.init(jax.random.PRNGKey(42), x)
out, state = f.apply(params, state, None, x)
print(out)
```

**Comment by tomhennigan** [comment]
Re creating submodules repeatedly in `__call__`. Yes this is fine. In Haiku (as with Sonnet 1) all sharing of state is based on module names. These names are established at construction time and take into account the parent module name and current method name.

When you call a method on a module we establish a unique (within the application of the method) name for any submodules you create, these names are discarded when the method returns, as such when you call the method again you will end up getting the same names (assuming that execution of your method is deterministic).

I'd suggest playing with this in a colab to get a better understanding, in particular printing `mod.module_name` might be useful.

For example:

```python
class MyModule(hk.Module):
  def __call__(self, x):
    l1 = hk.Linear(1)  # module_name: `my_module/linear` (for m1)   OR `my_module_1/linear` (for m2)
    l2 = hk.Linear(1)  # module_name: `my_module/linear_1` (for m1) OR `my_module_1/linear_1` (for m2)
    return l2(jax.nn.relu(l1(x)))

def f(x):
  m1 = MyModule()  # module_name: `my_module`
  m2 = MyModule()  # module_name: `my_module_1`
  x = m2(m1(x))
  x = m2(m1(x))  # Will recreate the Python objects l1/l2 but these will be given the same name by haiku so parameters will be reused.
  return x
```

If you prefer it is of course fine to use a more traditional Python style and keep modules as object properties assigned in the constructor, this is however a bit more verbose and many researchers prefer the convenience afforded by defining and using their module on the same line(s) of code:

```python
class MyModule(hk.Module):
  def __init__(self, name=None):
    super().__init__(name=name)
    self.l1 = hk.Linear(1)  # module_name: `my_module/~/linear` (for m1)   OR `my_module_1/~/linear` (for m2)
    self.l2 = hk.Linear(1)  # module_name: `my_module/~/linear_1` (for m1) OR `my_module_1/~/linear_1` (for m2)

  def __call__(self, x):
    return self.l2(jax.nn.relu(self.l1(x)))

def f(x):
  m1 = MyModule()  # module_name: `my_module`
  m2 = MyModule()  # module_name: `my_module_1`
  x = m2(m1(x))
  x = m2(m1(x))
  return x
```

**Comment by mil-ad** [comment]
Thanks @tomhennigan for the clear explanation. I think some of this could really go into the official documentation as it helps in establishing a mental model of how things work.
